version: "3.8"
services:
  nginx:
    image: nginx:1.17.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
  app1:
    build:
      context: ./app1
    ports:
      - "3000:3000"
    volumes:
      - ./app1:/app
  app2:
    build:
      context: ./app2
    ports:
      - "3001:3000"
    volumes:
      - ./app2:/app
